version: '3'
services:
        
    comm_gateway:
      container_name: "communication_gateway"
      build: 
        context: comm_gateway
      ports:
        - "5084:5084"
      environment:
        # only the version of api might change
        - FB_API_URL=https://graph.facebook.com/v7.0/me/messages 
        
        # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # depends_on:
      #   - chatbot_socket
      volumes:          
        - ./comm_gateway:/opt/workdir 
        - logging_volume:/opt/logging
    
volumes:
#   # redis-data:
#   grafana-data:
  logging_volume: