apiVersion: extensions/v1beta1

kind: Ingress
metadata:
  name: ingress-comm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: prod
spec:
  rules:
  - http:
      paths:
      - path: / # the root path is pointing to prod
        backend:
          serviceName: comm
          servicePort: 5000
      - path: /prod
        backend:
          serviceName: comm
          servicePort: 5000
